[api]
hostname = "api.wordpress.org"
querystring = "/plugins/info/1.2/?action=query_plugins&request[browse]=popular&request[page]="
[plugins]
active_install = 4000000
[download]
directory = "data"
[extraction]
directory = "extracted_plugins"